// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/vtr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session status enum
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_RUNNING     SessionStatus = 1
	SessionStatus_SESSION_STATUS_EXITED      SessionStatus = 2
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_RUNNING",
		2: "SESSION_STATUS_EXITED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_RUNNING":     1,
		"SESSION_STATUS_EXITED":      2,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vtr_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_proto_vtr_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{0}
}

// Session represents a named PTY session
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=vtr.SessionStatus" json:"status,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // only valid when status = EXITED
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExitedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=exited_at,json=exitedAt,proto3" json:"exited_at,omitempty"` // only valid when status = EXITED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_vtr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Session) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Session) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

// Session management messages
type SpawnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                                                   // default: server default shell (config or $SHELL)
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // default: $HOME
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // merged with default env
	Cols          int32                  `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`                                                                        // default: 80
	Rows          int32                  `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`                                                                        // default: 24
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnRequest) Reset() {
	*x = SpawnRequest{}
	mi := &file_proto_vtr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest) ProtoMessage() {}

func (x *SpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest.ProtoReflect.Descriptor instead.
func (*SpawnRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpawnRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SpawnRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SpawnRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SpawnRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *SpawnRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type SpawnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnResponse) Reset() {
	*x = SpawnResponse{}
	mi := &file_proto_vtr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse) ProtoMessage() {}

func (x *SpawnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse.ProtoReflect.Descriptor instead.
func (*SpawnResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{2}
}

func (x *SpawnResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_vtr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{3}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_vtr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_vtr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{5}
}

func (x *InfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proto_vtr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{6}
}

func (x *InfoResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"` // TERM, KILL, INT; default: TERM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_proto_vtr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{7}
}

func (x *KillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KillRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_proto_vtr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{8}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_vtr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_proto_vtr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{10}
}

// Screen operations messages
type GetScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenRequest) Reset() {
	*x = GetScreenRequest{}
	mi := &file_proto_vtr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenRequest) ProtoMessage() {}

func (x *GetScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenRequest.ProtoReflect.Descriptor instead.
func (*GetScreenRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{11}
}

func (x *GetScreenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ScreenCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Char          string                 `protobuf:"bytes,1,opt,name=char,proto3" json:"char,omitempty"`
	FgColor       int32                  `protobuf:"varint,2,opt,name=fg_color,json=fgColor,proto3" json:"fg_color,omitempty"` // RGB packed
	BgColor       int32                  `protobuf:"varint,3,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"` // RGB packed
	Attributes    uint32                 `protobuf:"varint,4,opt,name=attributes,proto3" json:"attributes,omitempty"`          // bold=0x01, italic=0x02, underline=0x04, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenCell) Reset() {
	*x = ScreenCell{}
	mi := &file_proto_vtr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenCell) ProtoMessage() {}

func (x *ScreenCell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenCell.ProtoReflect.Descriptor instead.
func (*ScreenCell) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{12}
}

func (x *ScreenCell) GetChar() string {
	if x != nil {
		return x.Char
	}
	return ""
}

func (x *ScreenCell) GetFgColor() int32 {
	if x != nil {
		return x.FgColor
	}
	return 0
}

func (x *ScreenCell) GetBgColor() int32 {
	if x != nil {
		return x.BgColor
	}
	return 0
}

func (x *ScreenCell) GetAttributes() uint32 {
	if x != nil {
		return x.Attributes
	}
	return 0
}

type ScreenRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*ScreenCell          `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenRow) Reset() {
	*x = ScreenRow{}
	mi := &file_proto_vtr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenRow) ProtoMessage() {}

func (x *ScreenRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenRow.ProtoReflect.Descriptor instead.
func (*ScreenRow) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{13}
}

func (x *ScreenRow) GetCells() []*ScreenCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type GetScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	CursorX       int32                  `protobuf:"varint,4,opt,name=cursor_x,json=cursorX,proto3" json:"cursor_x,omitempty"`
	CursorY       int32                  `protobuf:"varint,5,opt,name=cursor_y,json=cursorY,proto3" json:"cursor_y,omitempty"`
	ScreenRows    []*ScreenRow           `protobuf:"bytes,6,rep,name=screen_rows,json=screenRows,proto3" json:"screen_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenResponse) Reset() {
	*x = GetScreenResponse{}
	mi := &file_proto_vtr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenResponse) ProtoMessage() {}

func (x *GetScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenResponse.ProtoReflect.Descriptor instead.
func (*GetScreenResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{14}
}

func (x *GetScreenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetScreenResponse) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *GetScreenResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *GetScreenResponse) GetCursorX() int32 {
	if x != nil {
		return x.CursorX
	}
	return 0
}

func (x *GetScreenResponse) GetCursorY() int32 {
	if x != nil {
		return x.CursorY
	}
	return 0
}

func (x *GetScreenResponse) GetScreenRows() []*ScreenRow {
	if x != nil {
		return x.ScreenRows
	}
	return nil
}

type GrepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"` // regex (RE2)
	ContextBefore int32                  `protobuf:"varint,3,opt,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	ContextAfter  int32                  `protobuf:"varint,4,opt,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
	MaxMatches    int32                  `protobuf:"varint,5,opt,name=max_matches,json=maxMatches,proto3" json:"max_matches,omitempty"` // default: 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepRequest) Reset() {
	*x = GrepRequest{}
	mi := &file_proto_vtr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepRequest) ProtoMessage() {}

func (x *GrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepRequest.ProtoReflect.Descriptor instead.
func (*GrepRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{15}
}

func (x *GrepRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrepRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GrepRequest) GetContextBefore() int32 {
	if x != nil {
		return x.ContextBefore
	}
	return 0
}

func (x *GrepRequest) GetContextAfter() int32 {
	if x != nil {
		return x.ContextAfter
	}
	return 0
}

func (x *GrepRequest) GetMaxMatches() int32 {
	if x != nil {
		return x.MaxMatches
	}
	return 0
}

type GrepMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    int32                  `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"` // 0-based, relative to scrollback start
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	ContextBefore []string               `protobuf:"bytes,3,rep,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	ContextAfter  []string               `protobuf:"bytes,4,rep,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepMatch) Reset() {
	*x = GrepMatch{}
	mi := &file_proto_vtr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepMatch) ProtoMessage() {}

func (x *GrepMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepMatch.ProtoReflect.Descriptor instead.
func (*GrepMatch) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{16}
}

func (x *GrepMatch) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *GrepMatch) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *GrepMatch) GetContextBefore() []string {
	if x != nil {
		return x.ContextBefore
	}
	return nil
}

func (x *GrepMatch) GetContextAfter() []string {
	if x != nil {
		return x.ContextAfter
	}
	return nil
}

type GrepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*GrepMatch           `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepResponse) Reset() {
	*x = GrepResponse{}
	mi := &file_proto_vtr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepResponse) ProtoMessage() {}

func (x *GrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepResponse.ProtoReflect.Descriptor instead.
func (*GrepResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{17}
}

func (x *GrepResponse) GetMatches() []*GrepMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// Input operations messages
type SendTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_proto_vtr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{18}
}

func (x *SendTextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextResponse) Reset() {
	*x = SendTextResponse{}
	mi := &file_proto_vtr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextResponse) ProtoMessage() {}

func (x *SendTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextResponse.ProtoReflect.Descriptor instead.
func (*SendTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{19}
}

type SendKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // enter, tab, escape, up, down, left, right, backspace, delete, ctrl+c, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendKeyRequest) Reset() {
	*x = SendKeyRequest{}
	mi := &file_proto_vtr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyRequest) ProtoMessage() {}

func (x *SendKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyRequest.ProtoReflect.Descriptor instead.
func (*SendKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{20}
}

func (x *SendKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SendKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendKeyResponse) Reset() {
	*x = SendKeyResponse{}
	mi := &file_proto_vtr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyResponse) ProtoMessage() {}

func (x *SendKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyResponse.ProtoReflect.Descriptor instead.
func (*SendKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{21}
}

type SendBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBytesRequest) Reset() {
	*x = SendBytesRequest{}
	mi := &file_proto_vtr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBytesRequest) ProtoMessage() {}

func (x *SendBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBytesRequest.ProtoReflect.Descriptor instead.
func (*SendBytesRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{22}
}

func (x *SendBytesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendBytesRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBytesResponse) Reset() {
	*x = SendBytesResponse{}
	mi := &file_proto_vtr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBytesResponse) ProtoMessage() {}

func (x *SendBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBytesResponse.ProtoReflect.Descriptor instead.
func (*SendBytesResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{23}
}

type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_proto_vtr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{24}
}

func (x *ResizeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResizeRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_proto_vtr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{25}
}

// Blocking operations messages
type WaitForRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"` // regex (RE2), matches output after request starts
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // overall deadline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForRequest) Reset() {
	*x = WaitForRequest{}
	mi := &file_proto_vtr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForRequest) ProtoMessage() {}

func (x *WaitForRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForRequest.ProtoReflect.Descriptor instead.
func (*WaitForRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{26}
}

func (x *WaitForRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WaitForRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *WaitForRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type WaitForResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	MatchedLine   string                 `protobuf:"bytes,2,opt,name=matched_line,json=matchedLine,proto3" json:"matched_line,omitempty"`
	TimedOut      bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForResponse) Reset() {
	*x = WaitForResponse{}
	mi := &file_proto_vtr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForResponse) ProtoMessage() {}

func (x *WaitForResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForResponse.ProtoReflect.Descriptor instead.
func (*WaitForResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{27}
}

func (x *WaitForResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *WaitForResponse) GetMatchedLine() string {
	if x != nil {
		return x.MatchedLine
	}
	return ""
}

func (x *WaitForResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type WaitForIdleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdleDuration  *durationpb.Duration   `protobuf:"bytes,2,opt,name=idle_duration,json=idleDuration,proto3" json:"idle_duration,omitempty"` // default: 5s of silence
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`                               // overall deadline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForIdleRequest) Reset() {
	*x = WaitForIdleRequest{}
	mi := &file_proto_vtr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForIdleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForIdleRequest) ProtoMessage() {}

func (x *WaitForIdleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForIdleRequest.ProtoReflect.Descriptor instead.
func (*WaitForIdleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{28}
}

func (x *WaitForIdleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WaitForIdleRequest) GetIdleDuration() *durationpb.Duration {
	if x != nil {
		return x.IdleDuration
	}
	return nil
}

func (x *WaitForIdleRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type WaitForIdleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idle          bool                   `protobuf:"varint,1,opt,name=idle,proto3" json:"idle,omitempty"`
	TimedOut      bool                   `protobuf:"varint,2,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForIdleResponse) Reset() {
	*x = WaitForIdleResponse{}
	mi := &file_proto_vtr_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForIdleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForIdleResponse) ProtoMessage() {}

func (x *WaitForIdleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForIdleResponse.ProtoReflect.Descriptor instead.
func (*WaitForIdleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{29}
}

func (x *WaitForIdleResponse) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

func (x *WaitForIdleResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

// Streaming messages
type SubscribeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IncludeScreenUpdates bool                   `protobuf:"varint,2,opt,name=include_screen_updates,json=includeScreenUpdates,proto3" json:"include_screen_updates,omitempty"`
	IncludeRawOutput     bool                   `protobuf:"varint,3,opt,name=include_raw_output,json=includeRawOutput,proto3" json:"include_raw_output,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_vtr_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{30}
}

func (x *SubscribeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubscribeRequest) GetIncludeScreenUpdates() bool {
	if x != nil {
		return x.IncludeScreenUpdates
	}
	return false
}

func (x *SubscribeRequest) GetIncludeRawOutput() bool {
	if x != nil {
		return x.IncludeRawOutput
	}
	return false
}

type ScreenUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        *GetScreenResponse     `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenUpdate) Reset() {
	*x = ScreenUpdate{}
	mi := &file_proto_vtr_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenUpdate) ProtoMessage() {}

func (x *ScreenUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenUpdate.ProtoReflect.Descriptor instead.
func (*ScreenUpdate) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{31}
}

func (x *ScreenUpdate) GetScreen() *GetScreenResponse {
	if x != nil {
		return x.Screen
	}
	return nil
}

type SessionExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExited) Reset() {
	*x = SessionExited{}
	mi := &file_proto_vtr_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExited) ProtoMessage() {}

func (x *SessionExited) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExited.ProtoReflect.Descriptor instead.
func (*SessionExited) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{32}
}

func (x *SessionExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type SubscribeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SubscribeEvent_ScreenUpdate
	//	*SubscribeEvent_RawOutput
	//	*SubscribeEvent_SessionExited
	Event         isSubscribeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEvent) Reset() {
	*x = SubscribeEvent{}
	mi := &file_proto_vtr_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEvent) ProtoMessage() {}

func (x *SubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEvent.ProtoReflect.Descriptor instead.
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{33}
}

func (x *SubscribeEvent) GetEvent() isSubscribeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscribeEvent) GetScreenUpdate() *ScreenUpdate {
	if x != nil {
		if x, ok := x.Event.(*SubscribeEvent_ScreenUpdate); ok {
			return x.ScreenUpdate
		}
	}
	return nil
}

func (x *SubscribeEvent) GetRawOutput() []byte {
	if x != nil {
		if x, ok := x.Event.(*SubscribeEvent_RawOutput); ok {
			return x.RawOutput
		}
	}
	return nil
}

func (x *SubscribeEvent) GetSessionExited() *SessionExited {
	if x != nil {
		if x, ok := x.Event.(*SubscribeEvent_SessionExited); ok {
			return x.SessionExited
		}
	}
	return nil
}

type isSubscribeEvent_Event interface {
	isSubscribeEvent_Event()
}

type SubscribeEvent_ScreenUpdate struct {
	ScreenUpdate *ScreenUpdate `protobuf:"bytes,1,opt,name=screen_update,json=screenUpdate,proto3,oneof"`
}

type SubscribeEvent_RawOutput struct {
	RawOutput []byte `protobuf:"bytes,2,opt,name=raw_output,json=rawOutput,proto3,oneof"`
}

type SubscribeEvent_SessionExited struct {
	SessionExited *SessionExited `protobuf:"bytes,3,opt,name=session_exited,json=sessionExited,proto3,oneof"`
}

func (*SubscribeEvent_ScreenUpdate) isSubscribeEvent_Event() {}

func (*SubscribeEvent_RawOutput) isSubscribeEvent_Event() {}

func (*SubscribeEvent_SessionExited) isSubscribeEvent_Event() {}

// Recording messages (P2)
type DumpAsciinemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpAsciinemaRequest) Reset() {
	*x = DumpAsciinemaRequest{}
	mi := &file_proto_vtr_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpAsciinemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpAsciinemaRequest) ProtoMessage() {}

func (x *DumpAsciinemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpAsciinemaRequest.ProtoReflect.Descriptor instead.
func (*DumpAsciinemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{34}
}

func (x *DumpAsciinemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DumpAsciinemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // asciinema v2 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpAsciinemaResponse) Reset() {
	*x = DumpAsciinemaResponse{}
	mi := &file_proto_vtr_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpAsciinemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpAsciinemaResponse) ProtoMessage() {}

func (x *DumpAsciinemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vtr_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpAsciinemaResponse.ProtoReflect.Descriptor instead.
func (*DumpAsciinemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_vtr_proto_rawDescGZIP(), []int{35}
}

func (x *DumpAsciinemaResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_vtr_proto protoreflect.FileDescriptor

const file_proto_vtr_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/vtr.proto\x12\x03vtr\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x82\x02\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.vtr.SessionStatusR\x06status\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\texited_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bexitedAt\"\xeb\x01\n" +
	"\fSpawnRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12,\n" +
	"\x03env\x18\x04 \x03(\v2\x1a.vtr.SpawnRequest.EnvEntryR\x03env\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\rSpawnResponse\x12&\n" +
	"\asession\x18\x01 \x01(\v2\f.vtr.SessionR\asession\"\r\n" +
	"\vListRequest\"8\n" +
	"\fListResponse\x12(\n" +
	"\bsessions\x18\x01 \x03(\v2\f.vtr.SessionR\bsessions\"!\n" +
	"\vInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\fInfoResponse\x12&\n" +
	"\asession\x18\x01 \x01(\v2\f.vtr.SessionR\asession\"9\n" +
	"\vKillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\x0e\n" +
	"\fKillResponse\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x10\n" +
	"\x0eRemoveResponse\"&\n" +
	"\x10GetScreenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"v\n" +
	"\n" +
	"ScreenCell\x12\x12\n" +
	"\x04char\x18\x01 \x01(\tR\x04char\x12\x19\n" +
	"\bfg_color\x18\x02 \x01(\x05R\afgColor\x12\x19\n" +
	"\bbg_color\x18\x03 \x01(\x05R\abgColor\x12\x1e\n" +
	"\n" +
	"attributes\x18\x04 \x01(\rR\n" +
	"attributes\"2\n" +
	"\tScreenRow\x12%\n" +
	"\x05cells\x18\x01 \x03(\v2\x0f.vtr.ScreenCellR\x05cells\"\xb6\x01\n" +
	"\x11GetScreenResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12\x19\n" +
	"\bcursor_x\x18\x04 \x01(\x05R\acursorX\x12\x19\n" +
	"\bcursor_y\x18\x05 \x01(\x05R\acursorY\x12/\n" +
	"\vscreen_rows\x18\x06 \x03(\v2\x0e.vtr.ScreenRowR\n" +
	"screenRows\"\xa8\x01\n" +
	"\vGrepRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12%\n" +
	"\x0econtext_before\x18\x03 \x01(\x05R\rcontextBefore\x12#\n" +
	"\rcontext_after\x18\x04 \x01(\x05R\fcontextAfter\x12\x1f\n" +
	"\vmax_matches\x18\x05 \x01(\x05R\n" +
	"maxMatches\"\x8c\x01\n" +
	"\tGrepMatch\x12\x1f\n" +
	"\vline_number\x18\x01 \x01(\x05R\n" +
	"lineNumber\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12%\n" +
	"\x0econtext_before\x18\x03 \x03(\tR\rcontextBefore\x12#\n" +
	"\rcontext_after\x18\x04 \x03(\tR\fcontextAfter\"8\n" +
	"\fGrepResponse\x12(\n" +
	"\amatches\x18\x01 \x03(\v2\x0e.vtr.GrepMatchR\amatches\"9\n" +
	"\x0fSendTextRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x12\n" +
	"\x10SendTextResponse\"6\n" +
	"\x0eSendKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x11\n" +
	"\x0fSendKeyResponse\":\n" +
	"\x10SendBytesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x13\n" +
	"\x11SendBytesResponse\"K\n" +
	"\rResizeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\"\x10\n" +
	"\x0eResizeResponse\"s\n" +
	"\x0eWaitForRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"k\n" +
	"\x0fWaitForResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12!\n" +
	"\fmatched_line\x18\x02 \x01(\tR\vmatchedLine\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\"\x9d\x01\n" +
	"\x12WaitForIdleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\ridle_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\fidleDuration\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"F\n" +
	"\x13WaitForIdleResponse\x12\x12\n" +
	"\x04idle\x18\x01 \x01(\bR\x04idle\x12\x1b\n" +
	"\ttimed_out\x18\x02 \x01(\bR\btimedOut\"\x8a\x01\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x16include_screen_updates\x18\x02 \x01(\bR\x14includeScreenUpdates\x12,\n" +
	"\x12include_raw_output\x18\x03 \x01(\bR\x10includeRawOutput\">\n" +
	"\fScreenUpdate\x12.\n" +
	"\x06screen\x18\x01 \x01(\v2\x16.vtr.GetScreenResponseR\x06screen\",\n" +
	"\rSessionExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"\xb1\x01\n" +
	"\x0eSubscribeEvent\x128\n" +
	"\rscreen_update\x18\x01 \x01(\v2\x11.vtr.ScreenUpdateH\x00R\fscreenUpdate\x12\x1f\n" +
	"\n" +
	"raw_output\x18\x02 \x01(\fH\x00R\trawOutput\x12;\n" +
	"\x0esession_exited\x18\x03 \x01(\v2\x12.vtr.SessionExitedH\x00R\rsessionExitedB\a\n" +
	"\x05event\"*\n" +
	"\x14DumpAsciinemaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15DumpAsciinemaResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*f\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x01\x12\x19\n" +
	"\x15SESSION_STATUS_EXITED\x10\x022\xb1\x06\n" +
	"\x03VTR\x12.\n" +
	"\x05Spawn\x12\x11.vtr.SpawnRequest\x1a\x12.vtr.SpawnResponse\x12+\n" +
	"\x04List\x12\x10.vtr.ListRequest\x1a\x11.vtr.ListResponse\x12+\n" +
	"\x04Info\x12\x10.vtr.InfoRequest\x1a\x11.vtr.InfoResponse\x12+\n" +
	"\x04Kill\x12\x10.vtr.KillRequest\x1a\x11.vtr.KillResponse\x121\n" +
	"\x06Remove\x12\x12.vtr.RemoveRequest\x1a\x13.vtr.RemoveResponse\x12:\n" +
	"\tGetScreen\x12\x15.vtr.GetScreenRequest\x1a\x16.vtr.GetScreenResponse\x12+\n" +
	"\x04Grep\x12\x10.vtr.GrepRequest\x1a\x11.vtr.GrepResponse\x127\n" +
	"\bSendText\x12\x14.vtr.SendTextRequest\x1a\x15.vtr.SendTextResponse\x124\n" +
	"\aSendKey\x12\x13.vtr.SendKeyRequest\x1a\x14.vtr.SendKeyResponse\x12:\n" +
	"\tSendBytes\x12\x15.vtr.SendBytesRequest\x1a\x16.vtr.SendBytesResponse\x121\n" +
	"\x06Resize\x12\x12.vtr.ResizeRequest\x1a\x13.vtr.ResizeResponse\x124\n" +
	"\aWaitFor\x12\x13.vtr.WaitForRequest\x1a\x14.vtr.WaitForResponse\x12@\n" +
	"\vWaitForIdle\x12\x17.vtr.WaitForIdleRequest\x1a\x18.vtr.WaitForIdleResponse\x129\n" +
	"\tSubscribe\x12\x15.vtr.SubscribeRequest\x1a\x13.vtr.SubscribeEvent0\x01\x12F\n" +
	"\rDumpAsciinema\x12\x19.vtr.DumpAsciinemaRequest\x1a\x1a.vtr.DumpAsciinemaResponseB\x1fZ\x1dgithub.com/advait/vtrpc/protob\x06proto3"

var (
	file_proto_vtr_proto_rawDescOnce sync.Once
	file_proto_vtr_proto_rawDescData []byte
)

func file_proto_vtr_proto_rawDescGZIP() []byte {
	file_proto_vtr_proto_rawDescOnce.Do(func() {
		file_proto_vtr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vtr_proto_rawDesc), len(file_proto_vtr_proto_rawDesc)))
	})
	return file_proto_vtr_proto_rawDescData
}

var file_proto_vtr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_vtr_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_vtr_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: vtr.SessionStatus
	(*Session)(nil),               // 1: vtr.Session
	(*SpawnRequest)(nil),          // 2: vtr.SpawnRequest
	(*SpawnResponse)(nil),         // 3: vtr.SpawnResponse
	(*ListRequest)(nil),           // 4: vtr.ListRequest
	(*ListResponse)(nil),          // 5: vtr.ListResponse
	(*InfoRequest)(nil),           // 6: vtr.InfoRequest
	(*InfoResponse)(nil),          // 7: vtr.InfoResponse
	(*KillRequest)(nil),           // 8: vtr.KillRequest
	(*KillResponse)(nil),          // 9: vtr.KillResponse
	(*RemoveRequest)(nil),         // 10: vtr.RemoveRequest
	(*RemoveResponse)(nil),        // 11: vtr.RemoveResponse
	(*GetScreenRequest)(nil),      // 12: vtr.GetScreenRequest
	(*ScreenCell)(nil),            // 13: vtr.ScreenCell
	(*ScreenRow)(nil),             // 14: vtr.ScreenRow
	(*GetScreenResponse)(nil),     // 15: vtr.GetScreenResponse
	(*GrepRequest)(nil),           // 16: vtr.GrepRequest
	(*GrepMatch)(nil),             // 17: vtr.GrepMatch
	(*GrepResponse)(nil),          // 18: vtr.GrepResponse
	(*SendTextRequest)(nil),       // 19: vtr.SendTextRequest
	(*SendTextResponse)(nil),      // 20: vtr.SendTextResponse
	(*SendKeyRequest)(nil),        // 21: vtr.SendKeyRequest
	(*SendKeyResponse)(nil),       // 22: vtr.SendKeyResponse
	(*SendBytesRequest)(nil),      // 23: vtr.SendBytesRequest
	(*SendBytesResponse)(nil),     // 24: vtr.SendBytesResponse
	(*ResizeRequest)(nil),         // 25: vtr.ResizeRequest
	(*ResizeResponse)(nil),        // 26: vtr.ResizeResponse
	(*WaitForRequest)(nil),        // 27: vtr.WaitForRequest
	(*WaitForResponse)(nil),       // 28: vtr.WaitForResponse
	(*WaitForIdleRequest)(nil),    // 29: vtr.WaitForIdleRequest
	(*WaitForIdleResponse)(nil),   // 30: vtr.WaitForIdleResponse
	(*SubscribeRequest)(nil),      // 31: vtr.SubscribeRequest
	(*ScreenUpdate)(nil),          // 32: vtr.ScreenUpdate
	(*SessionExited)(nil),         // 33: vtr.SessionExited
	(*SubscribeEvent)(nil),        // 34: vtr.SubscribeEvent
	(*DumpAsciinemaRequest)(nil),  // 35: vtr.DumpAsciinemaRequest
	(*DumpAsciinemaResponse)(nil), // 36: vtr.DumpAsciinemaResponse
	nil,                           // 37: vtr.SpawnRequest.EnvEntry
	(*timestamppb.Timestamp)(nil), // 38: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 39: google.protobuf.Duration
}
var file_proto_vtr_proto_depIdxs = []int32{
	0,  // 0: vtr.Session.status:type_name -> vtr.SessionStatus
	38, // 1: vtr.Session.created_at:type_name -> google.protobuf.Timestamp
	38, // 2: vtr.Session.exited_at:type_name -> google.protobuf.Timestamp
	37, // 3: vtr.SpawnRequest.env:type_name -> vtr.SpawnRequest.EnvEntry
	1,  // 4: vtr.SpawnResponse.session:type_name -> vtr.Session
	1,  // 5: vtr.ListResponse.sessions:type_name -> vtr.Session
	1,  // 6: vtr.InfoResponse.session:type_name -> vtr.Session
	13, // 7: vtr.ScreenRow.cells:type_name -> vtr.ScreenCell
	14, // 8: vtr.GetScreenResponse.screen_rows:type_name -> vtr.ScreenRow
	17, // 9: vtr.GrepResponse.matches:type_name -> vtr.GrepMatch
	39, // 10: vtr.WaitForRequest.timeout:type_name -> google.protobuf.Duration
	39, // 11: vtr.WaitForIdleRequest.idle_duration:type_name -> google.protobuf.Duration
	39, // 12: vtr.WaitForIdleRequest.timeout:type_name -> google.protobuf.Duration
	15, // 13: vtr.ScreenUpdate.screen:type_name -> vtr.GetScreenResponse
	32, // 14: vtr.SubscribeEvent.screen_update:type_name -> vtr.ScreenUpdate
	33, // 15: vtr.SubscribeEvent.session_exited:type_name -> vtr.SessionExited
	2,  // 16: vtr.VTR.Spawn:input_type -> vtr.SpawnRequest
	4,  // 17: vtr.VTR.List:input_type -> vtr.ListRequest
	6,  // 18: vtr.VTR.Info:input_type -> vtr.InfoRequest
	8,  // 19: vtr.VTR.Kill:input_type -> vtr.KillRequest
	10, // 20: vtr.VTR.Remove:input_type -> vtr.RemoveRequest
	12, // 21: vtr.VTR.GetScreen:input_type -> vtr.GetScreenRequest
	16, // 22: vtr.VTR.Grep:input_type -> vtr.GrepRequest
	19, // 23: vtr.VTR.SendText:input_type -> vtr.SendTextRequest
	21, // 24: vtr.VTR.SendKey:input_type -> vtr.SendKeyRequest
	23, // 25: vtr.VTR.SendBytes:input_type -> vtr.SendBytesRequest
	25, // 26: vtr.VTR.Resize:input_type -> vtr.ResizeRequest
	27, // 27: vtr.VTR.WaitFor:input_type -> vtr.WaitForRequest
	29, // 28: vtr.VTR.WaitForIdle:input_type -> vtr.WaitForIdleRequest
	31, // 29: vtr.VTR.Subscribe:input_type -> vtr.SubscribeRequest
	35, // 30: vtr.VTR.DumpAsciinema:input_type -> vtr.DumpAsciinemaRequest
	3,  // 31: vtr.VTR.Spawn:output_type -> vtr.SpawnResponse
	5,  // 32: vtr.VTR.List:output_type -> vtr.ListResponse
	7,  // 33: vtr.VTR.Info:output_type -> vtr.InfoResponse
	9,  // 34: vtr.VTR.Kill:output_type -> vtr.KillResponse
	11, // 35: vtr.VTR.Remove:output_type -> vtr.RemoveResponse
	15, // 36: vtr.VTR.GetScreen:output_type -> vtr.GetScreenResponse
	18, // 37: vtr.VTR.Grep:output_type -> vtr.GrepResponse
	20, // 38: vtr.VTR.SendText:output_type -> vtr.SendTextResponse
	22, // 39: vtr.VTR.SendKey:output_type -> vtr.SendKeyResponse
	24, // 40: vtr.VTR.SendBytes:output_type -> vtr.SendBytesResponse
	26, // 41: vtr.VTR.Resize:output_type -> vtr.ResizeResponse
	28, // 42: vtr.VTR.WaitFor:output_type -> vtr.WaitForResponse
	30, // 43: vtr.VTR.WaitForIdle:output_type -> vtr.WaitForIdleResponse
	34, // 44: vtr.VTR.Subscribe:output_type -> vtr.SubscribeEvent
	36, // 45: vtr.VTR.DumpAsciinema:output_type -> vtr.DumpAsciinemaResponse
	31, // [31:46] is the sub-list for method output_type
	16, // [16:31] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_vtr_proto_init() }
func file_proto_vtr_proto_init() {
	if File_proto_vtr_proto != nil {
		return
	}
	file_proto_vtr_proto_msgTypes[33].OneofWrappers = []any{
		(*SubscribeEvent_ScreenUpdate)(nil),
		(*SubscribeEvent_RawOutput)(nil),
		(*SubscribeEvent_SessionExited)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vtr_proto_rawDesc), len(file_proto_vtr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vtr_proto_goTypes,
		DependencyIndexes: file_proto_vtr_proto_depIdxs,
		EnumInfos:         file_proto_vtr_proto_enumTypes,
		MessageInfos:      file_proto_vtr_proto_msgTypes,
	}.Build()
	File_proto_vtr_proto = out.File
	file_proto_vtr_proto_goTypes = nil
	file_proto_vtr_proto_depIdxs = nil
}
