// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/vtr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VTR_Spawn_FullMethodName         = "/vtr.VTR/Spawn"
	VTR_List_FullMethodName          = "/vtr.VTR/List"
	VTR_Info_FullMethodName          = "/vtr.VTR/Info"
	VTR_Kill_FullMethodName          = "/vtr.VTR/Kill"
	VTR_Remove_FullMethodName        = "/vtr.VTR/Remove"
	VTR_GetScreen_FullMethodName     = "/vtr.VTR/GetScreen"
	VTR_Grep_FullMethodName          = "/vtr.VTR/Grep"
	VTR_SendText_FullMethodName      = "/vtr.VTR/SendText"
	VTR_SendKey_FullMethodName       = "/vtr.VTR/SendKey"
	VTR_SendBytes_FullMethodName     = "/vtr.VTR/SendBytes"
	VTR_Resize_FullMethodName        = "/vtr.VTR/Resize"
	VTR_WaitFor_FullMethodName       = "/vtr.VTR/WaitFor"
	VTR_WaitForIdle_FullMethodName   = "/vtr.VTR/WaitForIdle"
	VTR_Subscribe_FullMethodName     = "/vtr.VTR/Subscribe"
	VTR_DumpAsciinema_FullMethodName = "/vtr.VTR/DumpAsciinema"
)

// VTRClient is the client API for VTR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VTRClient interface {
	// Session management
	Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// Screen operations
	GetScreen(ctx context.Context, in *GetScreenRequest, opts ...grpc.CallOption) (*GetScreenResponse, error)
	Grep(ctx context.Context, in *GrepRequest, opts ...grpc.CallOption) (*GrepResponse, error)
	// Input operations
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendTextResponse, error)
	SendKey(ctx context.Context, in *SendKeyRequest, opts ...grpc.CallOption) (*SendKeyResponse, error)
	SendBytes(ctx context.Context, in *SendBytesRequest, opts ...grpc.CallOption) (*SendBytesResponse, error)
	Resize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error)
	// Blocking operations
	WaitFor(ctx context.Context, in *WaitForRequest, opts ...grpc.CallOption) (*WaitForResponse, error)
	WaitForIdle(ctx context.Context, in *WaitForIdleRequest, opts ...grpc.CallOption) (*WaitForIdleResponse, error)
	// Streaming (for attach/web UI)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEvent], error)
	// Recording (P2)
	DumpAsciinema(ctx context.Context, in *DumpAsciinemaRequest, opts ...grpc.CallOption) (*DumpAsciinemaResponse, error)
}

type vTRClient struct {
	cc grpc.ClientConnInterface
}

func NewVTRClient(cc grpc.ClientConnInterface) VTRClient {
	return &vTRClient{cc}
}

func (c *vTRClient) Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResponse)
	err := c.cc.Invoke(ctx, VTR_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, VTR_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, VTR_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, VTR_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, VTR_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) GetScreen(ctx context.Context, in *GetScreenRequest, opts ...grpc.CallOption) (*GetScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScreenResponse)
	err := c.cc.Invoke(ctx, VTR_GetScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) Grep(ctx context.Context, in *GrepRequest, opts ...grpc.CallOption) (*GrepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrepResponse)
	err := c.cc.Invoke(ctx, VTR_Grep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTextResponse)
	err := c.cc.Invoke(ctx, VTR_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) SendKey(ctx context.Context, in *SendKeyRequest, opts ...grpc.CallOption) (*SendKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendKeyResponse)
	err := c.cc.Invoke(ctx, VTR_SendKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) SendBytes(ctx context.Context, in *SendBytesRequest, opts ...grpc.CallOption) (*SendBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBytesResponse)
	err := c.cc.Invoke(ctx, VTR_SendBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) Resize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeResponse)
	err := c.cc.Invoke(ctx, VTR_Resize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) WaitFor(ctx context.Context, in *WaitForRequest, opts ...grpc.CallOption) (*WaitForResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForResponse)
	err := c.cc.Invoke(ctx, VTR_WaitFor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) WaitForIdle(ctx context.Context, in *WaitForIdleRequest, opts ...grpc.CallOption) (*WaitForIdleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForIdleResponse)
	err := c.cc.Invoke(ctx, VTR_WaitForIdle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTRClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VTR_ServiceDesc.Streams[0], VTR_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VTR_SubscribeClient = grpc.ServerStreamingClient[SubscribeEvent]

func (c *vTRClient) DumpAsciinema(ctx context.Context, in *DumpAsciinemaRequest, opts ...grpc.CallOption) (*DumpAsciinemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DumpAsciinemaResponse)
	err := c.cc.Invoke(ctx, VTR_DumpAsciinema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VTRServer is the server API for VTR service.
// All implementations must embed UnimplementedVTRServer
// for forward compatibility.
type VTRServer interface {
	// Session management
	Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// Screen operations
	GetScreen(context.Context, *GetScreenRequest) (*GetScreenResponse, error)
	Grep(context.Context, *GrepRequest) (*GrepResponse, error)
	// Input operations
	SendText(context.Context, *SendTextRequest) (*SendTextResponse, error)
	SendKey(context.Context, *SendKeyRequest) (*SendKeyResponse, error)
	SendBytes(context.Context, *SendBytesRequest) (*SendBytesResponse, error)
	Resize(context.Context, *ResizeRequest) (*ResizeResponse, error)
	// Blocking operations
	WaitFor(context.Context, *WaitForRequest) (*WaitForResponse, error)
	WaitForIdle(context.Context, *WaitForIdleRequest) (*WaitForIdleResponse, error)
	// Streaming (for attach/web UI)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeEvent]) error
	// Recording (P2)
	DumpAsciinema(context.Context, *DumpAsciinemaRequest) (*DumpAsciinemaResponse, error)
	mustEmbedUnimplementedVTRServer()
}

// UnimplementedVTRServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVTRServer struct{}

func (UnimplementedVTRServer) Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedVTRServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVTRServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVTRServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedVTRServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedVTRServer) GetScreen(context.Context, *GetScreenRequest) (*GetScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScreen not implemented")
}
func (UnimplementedVTRServer) Grep(context.Context, *GrepRequest) (*GrepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Grep not implemented")
}
func (UnimplementedVTRServer) SendText(context.Context, *SendTextRequest) (*SendTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedVTRServer) SendKey(context.Context, *SendKeyRequest) (*SendKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendKey not implemented")
}
func (UnimplementedVTRServer) SendBytes(context.Context, *SendBytesRequest) (*SendBytesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBytes not implemented")
}
func (UnimplementedVTRServer) Resize(context.Context, *ResizeRequest) (*ResizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resize not implemented")
}
func (UnimplementedVTRServer) WaitFor(context.Context, *WaitForRequest) (*WaitForResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitFor not implemented")
}
func (UnimplementedVTRServer) WaitForIdle(context.Context, *WaitForIdleRequest) (*WaitForIdleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForIdle not implemented")
}
func (UnimplementedVTRServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedVTRServer) DumpAsciinema(context.Context, *DumpAsciinemaRequest) (*DumpAsciinemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DumpAsciinema not implemented")
}
func (UnimplementedVTRServer) mustEmbedUnimplementedVTRServer() {}
func (UnimplementedVTRServer) testEmbeddedByValue()             {}

// UnsafeVTRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VTRServer will
// result in compilation errors.
type UnsafeVTRServer interface {
	mustEmbedUnimplementedVTRServer()
}

func RegisterVTRServer(s grpc.ServiceRegistrar, srv VTRServer) {
	// If the following call panics, it indicates UnimplementedVTRServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VTR_ServiceDesc, srv)
}

func _VTR_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).Spawn(ctx, req.(*SpawnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_GetScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).GetScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_GetScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).GetScreen(ctx, req.(*GetScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_Grep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).Grep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_Grep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).Grep(ctx, req.(*GrepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_SendKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).SendKey(ctx, req.(*SendKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_SendBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).SendBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_SendBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).SendBytes(ctx, req.(*SendBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_Resize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).Resize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_Resize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).Resize(ctx, req.(*ResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_WaitFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).WaitFor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_WaitFor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).WaitFor(ctx, req.(*WaitForRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_WaitForIdle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForIdleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).WaitForIdle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_WaitForIdle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).WaitForIdle(ctx, req.(*WaitForIdleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTR_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VTRServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VTR_SubscribeServer = grpc.ServerStreamingServer[SubscribeEvent]

func _VTR_DumpAsciinema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpAsciinemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTRServer).DumpAsciinema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VTR_DumpAsciinema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTRServer).DumpAsciinema(ctx, req.(*DumpAsciinemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VTR_ServiceDesc is the grpc.ServiceDesc for VTR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VTR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vtr.VTR",
	HandlerType: (*VTRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _VTR_Spawn_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VTR_List_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _VTR_Info_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _VTR_Kill_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _VTR_Remove_Handler,
		},
		{
			MethodName: "GetScreen",
			Handler:    _VTR_GetScreen_Handler,
		},
		{
			MethodName: "Grep",
			Handler:    _VTR_Grep_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _VTR_SendText_Handler,
		},
		{
			MethodName: "SendKey",
			Handler:    _VTR_SendKey_Handler,
		},
		{
			MethodName: "SendBytes",
			Handler:    _VTR_SendBytes_Handler,
		},
		{
			MethodName: "Resize",
			Handler:    _VTR_Resize_Handler,
		},
		{
			MethodName: "WaitFor",
			Handler:    _VTR_WaitFor_Handler,
		},
		{
			MethodName: "WaitForIdle",
			Handler:    _VTR_WaitForIdle_Handler,
		},
		{
			MethodName: "DumpAsciinema",
			Handler:    _VTR_DumpAsciinema_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _VTR_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/vtr.proto",
}
